### ISSUE TITLE
markers_of_interest

### ISSUE THREAD

**Issue by Dannyxu123** [saeyslab/FlowSOM_protocol#2]
Hi! It's a really powerful tool to analyze flow data. But I am a little bit confused regarding whether markers_of_interest have to include all markers that have been stained during flow cytometry experiment. The problem that I ran into was that while most of the staining markers were consistent across a series of flow cytometry experiments, few of the markers were changed. Could these data still be able to integrate？

**Comment by KatrienQ** [comment]
Hi!
We recommend to include all the channels that would be considered during a manual gating (i.e. to identify the cell types). These are the lineage markers in the panel. Functional markers that were stained, are usually evaluated per FlowSOM (meta-)cluster afterwards by for example looking at the MFIs or percentage positives. Keep in mind to perform quality control on all the markers that are used during the complete data analysis, so both the lineage and functional markers.
Markers that are only used during the preprocessing for e.g. pre-gating should also not be used for the clustering.
