### ISSUE TITLE
Question on Purity

### ISSUE THREAD

**Issue by gmillerscripps** [saeyslab/FlowSOM_protocol#3]
Hello! I am looking through the protocol, and was wondering a couple of things related to purity. 

1. Why did you set n_meta = 8. did you know in advance that there were approximately 8 cell sub-types that you were interested in?

2. In the code below: 

```
Purity(realClusters = aggregate_labels,
       predictedClusters = GetClusters(fsom))
```

We compare the clusters against the aggregate labels (made up of 8 unique cell types), and compare to `GetClusters(fsom)`, which is made up of 100 unique clusters. Should we be using `GetMetaclusters()`? 

Thanks

**Comment by KatrienQ** [comment]
Hi!

To answer you first question, we first went for the default number of metaclusters first, i.e. 10. But then we saw that some cell types were in multiple metaclusters, so we were overclustering. That is when we tested out different numbers of metaclusters and decided that 8 was the best number for this panel and this dataset.

For your second question, we have 1 cell type for each cell in the aggregate (the one we used for training the FlowSOM model). The function evaluates the purity on cluster level, that is why we give in the cluster labels. If you have low purity scores here, you know you'll have low purities on metacluster level too and that you should increase the grid size of the SOM.
