### ISSUE TITLE
Can't get GetFlowJoLabels() to match gating in FlowJo workspace

### ISSUE THREAD

**Issue by gmillerscripps** [saeyslab/FlowSOM_protocol#4]
Hello, in the code below, I am getting the FlowJo labels from FlowJo using GetFlowJoLabels ( FlowSOM_2.8.0). 

```
# 20.(B) Check the consistency with manual labeling
# 20.(B)(i) Extract the gating information from the wsp file
gating <- GetFlowJoLabels(files = files,
                          wspFile = "Data/Raw/attachments/General_panel.wsp",
                          path = dir_raw)
```

I can't get table(gating$manual) to reflect what I am seeing in the FlowJo workspace. Some of them match, but not all. I had the same issue on my own dataset. Is there something I am not understanding about the use of GetFlowJoLabels?

![image](https://github.com/saeyslab/FlowSOM_protocol/assets/145794512/d9c639c1-6b78-49a4-b5db-d34e1daccea6)

![image](https://github.com/saeyslab/FlowSOM_protocol/assets/145794512/22fcc084-7a14-4b00-9020-7598d9b372b1)

Thanks!

**Comment by KatrienQ** [comment]
Hi, 

The unlabeled cells, are cells that are gated in none of the populations that were requested (e.g. do not pass the Single Cells gate). For the other populations, there are small differences between the FlowJo numbers and the numbers in R. This might result from slightly different transformations or edge events might be evaluated differently. I hope this clears out the confusion.
